[build]
  # directory to publish
  publish = "dist/"

  # Default build command.
  command = "npm run build"

  # Functions directory to deploy to AWS
  # functions = "functions/"

  # Node version
  environment = { NODE_VERSION = "16.4.1" }
